[package]
name = "gyeet"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
sha2 = "0.10"
reqwest = { version = "0.12", features = ["blocking", "json"] }
sevenz-rust = "0.6"
progress_bar = "1.4.0"